core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main_app')),
    path('', include('user.urls', namespace='user_app')),
]

admin.site.site_header = 'My admin panel'
admin.site.index_title = 'App Data' 

main/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user_app'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

main/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models


class UserModel(models.Model):
    user_name = models.CharField('User name', max_length=30)
    user_email = models.EmailField('User Email', unique=True)
    user_phone = models.CharField('User Phone', max_length=20, unique=True)
    user_password = models.CharField('Password', max_length=256)
    user_created = models.DateTimeField('Data created', auto_now_add=True)
    user_agreed = models.BooleanField('Agree', default=False)
    user_activated = models.BooleanField('Activated', default=False)
    user_banned = models.BooleanField('Banned', default=False)
    last_login = models.DateTimeField('Last visit', auto_now=True)

    class Meta:
        verbose_name = 'Users'
        verbose_name_plural = 'Users'
        ordering = ('-user_created',)

    def __str__(self):
        return self.user_name

user/forms.py
from django import forms


class RegisterForm(forms.Form):
    user_full_name = forms.CharField(max_length=50, label='Name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    user_email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control'}))
    user_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password')
    user_password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Repeat password')
    user_agree = forms.BooleanField(label='Rules agree', widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))


class LoginForm(forms.Form):
    user_email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control'}))
    user_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password')


class CheckSecretCodeForm(forms.Form):
    secret_code = forms.CharField(label='Code', widget=forms.TextInput(attrs={'class': 'form-control'}))


class ForgotPasswordForm(forms.Form):
    user_email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control'}))


class NewPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='New password')
    new_password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Repeat new password')

main/views.py
from django.shortcuts import render
from django.views import View


class IndexView(View):
    def get(self, request):
        return render(request, 'main/index.html')

user/views.py
from django.shortcuts import render
from django.views import View
from .mvc import get_all_users


class LoginView(View):
    def get(self, request):
        return render(request, 'user/login.html')


class RegisterView(View):
    def get(self, request):
        return render(request, 'user/register.html')


class ProfileView(View):
    def get(self, request):
        users = get_all_users()
        data = {'users': users}
        return render(request, 'user/profile.html', data)

main/templates/main/index.html
{% extends "base.html" %}

{% block main_content %}
<div class="row">
    <h1>App Main Page</h1>
</div>

{% endblock  %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

</head>
<body>

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light mb-5">
            <a class="navbar-brand" href="{% url 'main_app:index' %}">PRODSHOP</a>
            <div class="collapse navbar-collapse justify-content-end">
                <ul class="navbar-nav mr-auto">
                    <li><a href="{% url 'main_app:index' %}" class="nav-link">Main</a></li>
                    <li class="nav-item ms-2"><a class="btn btn-outline-dark" href="{% url 'user_app:login' %}">Login</a></li>
                    <li class="nav-item ms-2"><a class="btn btn-outline-dark" href="{% url 'user_app:register' %}">Register</a></li>
                    <li class="nav-item ms-2"><a class="btn btn-outline-dark" href="{% url 'user_app:profile' %}">Profile</a></li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="container">
        {% block main_content %}
        {% endblock %}
    </div>

</body>
</html>

user/templates/user/login.html
{% extends "base.html" %}

{% block main_content %}
<div class="row">
    <h1>Login Page</h1>
</div>

{% endblock  %}

user/templates/user/profile.html
{% extends "base.html" %}

{% block main_content %}
<div class="row">
    <h1>Profile Page</h1>

    <h2>USERS:</h2>
    {% for user in users %}
        <p>{{ user.user_name }} ; {{ user.user_email }} ; {{ user.user_phone }}</p>
    {% endfor %}
</div>


{% endblock  %}

user/templates/user/register.html
{% extends "base.html" %}

{% block main_content %}
<div class="row">
    <h1>Register Page</h1>
</div>

{% endblock  %}